version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: vehicles-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: vehicles-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  backend:
    build: ./backend
    container_name: vehicles-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
      MONGO_URL: mongodb://mongo:27017/vehicles

  vehicle-worker:
    build: ./vehicle-worker
    container_name: vehicles-worker
    restart: unless-stopped
    env_file:
      - ./vehicle-worker/.env
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672

  frontend:
    build: ./frontend
    container_name: vehicles-frontend
    restart: unless-stopped
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  mongo-data:
